gen:
	@protoc \
		--proto_path=protobuf "protobuf/read-excel.proto" \
		--go_out=services/common/genproto/read-excel --go_opt=paths=source_relative \
  	--go-grpc_out=services/common/genproto/read-excel --go-grpc_opt=paths=source_relative